/**
 * Định nghĩa chuẩn toàn bộ Action Types và Phân nhóm danh mục trong hệ thống Activity Log
 */

export const ACTIVITY_LOG_ACTIONS = {
  // 1. Xác thực & Tài khoản (Auth & Accounts)
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FIRST_TIME: 'LOGIN_FIRST_TIME',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  ADMIN_RESET_PASSWORD: 'ADMIN_RESET_PASSWORD',
  IMPERSONATE: 'IMPERSONATE',
  REVERT_IMPERSONATE: 'REVERT_IMPERSONATE',
  SWITCH_ROLE: 'SWITCH_ROLE',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  APPROVE_REGISTRATION: 'APPROVE_REGISTRATION',
  REJECT_REGISTRATION: 'REJECT_REGISTRATION',
  UPDATE_MY_PROFILE: 'UPDATE_MY_PROFILE',

  // 2. Sinh viên, Lớp học & Lớp trưởng (Students & Monitors)
  UPDATE_STUDENT_INFO: 'UPDATE_STUDENT_INFO',
  RECEIVE_STUDENT: 'RECEIVE_STUDENT',
  EXCLUDE_STUDENT: 'EXCLUDE_STUDENT',
  RESTORE_STUDENT: 'RESTORE_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  ASSIGN_MONITOR: 'ASSIGN_MONITOR',
  REMOVE_MONITOR: 'REMOVE_MONITOR',

  // 3. Đợt thi, Lịch thi, Tiền phòng & Phong bì (Exams & Rooms & Envelope)
  CREATE_BATCH: 'CREATE_BATCH',
  UPDATE_BATCH: 'UPDATE_BATCH',
  DELETE_BATCH: 'DELETE_BATCH',
  SET_ACTIVE_BATCH: 'SET_ACTIVE_BATCH',
  TOGGLE_BATCH_STATUS: 'TOGGLE_BATCH_STATUS',
  IMPORT_BATCH_FILE: 'IMPORT_BATCH_FILE',
  IMPORT_EXAM_SCHEDULE: 'IMPORT_EXAM_SCHEDULE',
  TOGGLE_EXAM_POSTPONE: 'TOGGLE_EXAM_POSTPONE',
  MARK_EXAM_POSTPONED: 'MARK_EXAM_POSTPONED',
  UNMARK_EXAM_POSTPONED: 'UNMARK_EXAM_POSTPONED',
  UPDATE_EXAM_ROOM_PRICE: 'UPDATE_EXAM_ROOM_PRICE',
  UPDATE_GLOBAL_PRICING_CONFIG: 'UPDATE_GLOBAL_PRICING_CONFIG',
  DELETE_EXAM_ROOM: 'DELETE_EXAM_ROOM',
  CLEAR_ALL_EXAM_ROOMS: 'CLEAR_ALL_EXAM_ROOMS',
  CLAIM_ENVELOPE: 'CLAIM_ENVELOPE',
  CANCEL_ENVELOPE_CLAIM: 'CANCEL_ENVELOPE_CLAIM',
  CLEAR_ALL_ENVELOPE_CLAIMS: 'CLEAR_ALL_ENVELOPE_CLAIMS',

  // 4. Cổng trường & Dữ liệu Sinh viên (QLDTTX, S-Link, LMS)
  SAVE_EXTERNAL_ACCOUNT: 'SAVE_EXTERNAL_ACCOUNT',
  SAVE_EXTERNAL_ACCOUNT_FAILED: 'SAVE_EXTERNAL_ACCOUNT_FAILED',
  TEST_EXTERNAL_ACCOUNT: 'TEST_EXTERNAL_ACCOUNT',
  TEST_EXTERNAL_ACCOUNT_CREDENTIALS: 'TEST_EXTERNAL_ACCOUNT_CREDENTIALS',
  TEST_EXTERNAL_ACCOUNT_FAILED: 'TEST_EXTERNAL_ACCOUNT_FAILED',
  BATCH_GET_TOKENS: 'BATCH_GET_TOKENS',
  DELETE_EXTERNAL_ACCOUNT: 'DELETE_EXTERNAL_ACCOUNT',
  SYNC_COURSE_REGISTRATION: 'SYNC_COURSE_REGISTRATION',
  SYNC_CLASS_REGISTRATION: 'SYNC_CLASS_REGISTRATION',
  DELETE_COURSE_REGISTRATION: 'DELETE_COURSE_REGISTRATION',
  PULL_STUDENT_GRADES: 'PULL_STUDENT_GRADES',
  PULL_STUDENT_TIMETABLE: 'PULL_STUDENT_TIMETABLE',
  PULL_STUDENT_EXAM_SCHEDULE: 'PULL_STUDENT_EXAM_SCHEDULE',
  QLDT_EXAM_SCHEDULE_CHANGED: 'QLDT_EXAM_SCHEDULE_CHANGED',
  COURSE_REGISTER: 'COURSE_REGISTER',
  COURSE_CANCEL: 'COURSE_CANCEL',
  LMS_REFRESH_COURSES: 'LMS_REFRESH_COURSES',
  SLINK_FORGOT_PASSWORD: 'SLINK_FORGOT_PASSWORD',
  SLINK_REFRESH_GRADES: 'SLINK_REFRESH_GRADES',
  SLINK_SYNC_GRADES: 'SLINK_SYNC_GRADES',
  SLINK_REFRESH_NOTIFICATIONS: 'SLINK_REFRESH_NOTIFICATIONS',
  SLINK_MARK_NOTIFICATION_READ: 'SLINK_MARK_NOTIFICATION_READ',

  // 5. Flow Automation Lớp trưởng (Monitor Flow)
  UPDATE_MONITOR_FLOW_CONFIG: 'UPDATE_MONITOR_FLOW_CONFIG',
  IMPORT_MONITOR_FLOW_CONFIG: 'IMPORT_MONITOR_FLOW_CONFIG',
  ENQUEUE_MONITOR_FLOW_BATCH: 'ENQUEUE_MONITOR_FLOW_BATCH',
  EXECUTE_MONITOR_FLOW_ACTION: 'EXECUTE_MONITOR_FLOW_ACTION',
  PULL_CLASS_COURSE_REGISTRATION: 'PULL_CLASS_COURSE_REGISTRATION',
  CANCEL_FLOW_QUEUE: 'CANCEL_FLOW_QUEUE',
  RETRY_FLOW_QUEUE: 'RETRY_FLOW_QUEUE',
  CLEAR_COMPLETED_FLOW_QUEUE: 'CLEAR_COMPLETED_FLOW_QUEUE',

  // 6. Global Sync & Cron Scheduler
  ENQUEUE_GLOBAL_SYNC_JOB: 'ENQUEUE_GLOBAL_SYNC_JOB',
  CANCEL_GLOBAL_QUEUE: 'CANCEL_GLOBAL_QUEUE',
  RETRY_GLOBAL_QUEUE: 'RETRY_GLOBAL_QUEUE',
  UPDATE_GLOBAL_SYNC_CONFIG: 'UPDATE_GLOBAL_SYNC_CONFIG',
  CLEAR_COMPLETED_GLOBAL_QUEUE: 'CLEAR_COMPLETED_GLOBAL_QUEUE',
  RECOVER_STUCK_QUEUE_JOBS: 'RECOVER_STUCK_QUEUE_JOBS',
  CRON_GLOBAL_SYNC_TRIGGER: 'CRON_GLOBAL_SYNC_TRIGGER',
  CRON_CLASS_REMINDERS: 'CRON_CLASS_REMINDERS',
  CRON_NEAREST_CLASS_SCHEDULE: 'CRON_NEAREST_CLASS_SCHEDULE',
  CRON_EXAM_REMINDERS: 'CRON_EXAM_REMINDERS',

  // 7. Telegram & Notifications
  SAVE_SYSTEM_TELEGRAM_BOT: 'SAVE_SYSTEM_TELEGRAM_BOT',
  TOGGLE_SYSTEM_TELEGRAM_BOT: 'TOGGLE_SYSTEM_TELEGRAM_BOT',
  SAVE_TELEGRAM_ADMIN_CONFIG: 'SAVE_TELEGRAM_ADMIN_CONFIG',
  CLEAR_TELEGRAM_QUEUE: 'CLEAR_TELEGRAM_QUEUE',
  BROADCAST_TELEGRAM: 'BROADCAST_TELEGRAM',
  CREATE_TELEGRAM_TOPIC: 'CREATE_TELEGRAM_TOPIC',
  CHECK_NEAREST_CLASS_SCHEDULE: 'CHECK_NEAREST_CLASS_SCHEDULE',
  SAVE_TELEGRAM_CONFIG: 'SAVE_TELEGRAM_CONFIG',
  TEST_TELEGRAM_CONFIG: 'TEST_TELEGRAM_CONFIG',
  TOGGLE_TELEGRAM_CONFIG: 'TOGGLE_TELEGRAM_CONFIG',
  DELETE_TELEGRAM_CONFIG: 'DELETE_TELEGRAM_CONFIG',

  // 8. Thông báo Hệ thống (Announcements)
  CREATE_ANNOUNCEMENT: 'CREATE_ANNOUNCEMENT',
  UPDATE_ANNOUNCEMENT: 'UPDATE_ANNOUNCEMENT',
  TOGGLE_ANNOUNCEMENT_STATUS: 'TOGGLE_ANNOUNCEMENT_STATUS',
  DELETE_ANNOUNCEMENT: 'DELETE_ANNOUNCEMENT',
  BULK_DELETE_ANNOUNCEMENTS: 'BULK_DELETE_ANNOUNCEMENTS',

  // 9. Sao lưu & Quản trị Hệ thống (Database Backup & Audit)
  DOWNLOAD_BACKUP: 'DOWNLOAD_BACKUP',
  EXPORT_SQL_DATABASE: 'EXPORT_SQL_DATABASE',
  RESTORE_DATABASE: 'RESTORE_DATABASE',
  SAVE_BACKUP_TELEGRAM_CONFIG: 'SAVE_BACKUP_TELEGRAM_CONFIG',
  TEST_BACKUP_TELEGRAM: 'TEST_BACKUP_TELEGRAM',
  SEND_BACKUP_TELEGRAM: 'SEND_BACKUP_TELEGRAM',
  CREATE_SERVER_BACKUP: 'CREATE_SERVER_BACKUP',
  DELETE_SERVER_BACKUP: 'DELETE_SERVER_BACKUP',
  DELETE_LOGS: 'DELETE_LOGS',
} as const;

export type ActivityLogAction = (typeof ACTIVITY_LOG_ACTIONS)[keyof typeof ACTIVITY_LOG_ACTIONS];

/**
 * Phân nhóm danh mục hoạt động để filter trên UI
 */
export const ACTION_CATEGORIES = {
  ALL: { id: 'ALL', label: 'Tất Cả Hoạt Động' },
  AUTH: { id: 'AUTH', label: 'Xác Thực & Tài Khoản' },
  STUDENT: { id: 'STUDENT', label: 'Sinh Viên & Lớp Học' },
  EXAM: { id: 'EXAM', label: 'Lịch Thi & Tiền Phòng' },
  PORTAL: { id: 'PORTAL', label: 'Cổng QLĐT / LMS / SLink' },
  FLOW: { id: 'FLOW', label: 'Flow ĐKMH Lớp Trưởng' },
  SYNC: { id: 'SYNC', label: 'Đồng Bộ & Cron' },
  TELEGRAM: { id: 'TELEGRAM', label: 'Telegram & Thông Báo' },
  SYSTEM: { id: 'SYSTEM', label: 'Hệ Thống & Sao Lưu' },
} as const;

export type ActionCategoryKey = keyof typeof ACTION_CATEGORIES;
